infractor_homepage:
    path: /
    defaults: { _controller: InfractorBundle:Default:index }

# New paths generados

get_login:
    path: /login
    defaults: { _controller: InfractorBundle:Login:getLogin }

logout:
    path: /logout
    defaults: { _controller: InfractorBundle:Login:doLogout }

register:
    path: /register
    defaults: { _controller: InfractorBundle:Login:register }

get_home:
    path: /home_infractor
    defaults: { _controller: InfractorBundle:Home:getHome }

detalles_multa:
    path: /detalles_multa
    defaults: { _controller: InfractorBundle:Home:detallesMulta }

elegir_pago:
    path: /pago/elegir
    defaults: { _controller: InfractorBundle:MetodoPago:getMetodosPago }

reclamar_multa:
    path: /reclamar_multa
    defaults: { _controller: InfractorBundle:Home:getHomeReclamar }

eleccion_tarjeta:
    path: /pago/pagoTarjeta
    defaults: { _controller: InfractorBundle:Pagos:comprobarYFinalizar }

eleccion_paypal:
    path: /pago/paypal
    defaults: { _controller: InfractorBundle:Pagos:comprobarYFinalizarPP }

introducir_coche:
    path: /introducir_coche
    defaults: { _controller: InfractorBundle:Coche:getFormularioCoche }
